### ISSUE TITLE
There are some odd numbers in phi function's results

### ISSUE THREAD

**Issue by shinichisaito** [Ironholds/primes#14] opened 2023-12-27 23:23 UTC
Hi,there!
I am amateur math fan.

Is Follows proper?
  
library(primes)
library(sjmisc)
1:10000 |> primes::phi() %>% .[is_odd(.)]

Thanks

**Comment by pegeler** [comment] 2023-12-28 18:08
Hi @Ironholds ,

You can assign this one to me. I'll take a look this weekend.

**Comment by pegeler** [comment] 2023-12-30 09:32
Thanks for bringing this bug to our attention, @shinichisaito ! We appreciate user feedback!
In the following, I will go over the steps I took to to reproduce the bug, perform analysis, and
share my conclusion.

## Background

The user @shinichisaito has found that the Euler’s totient function
(`phi`) in the `primes` package produces odd-numbered output for some
numbers 1 ≤ *n* ≤ 10000. This is problematic because we expect all
values to be even for *n* \> 2.

## Investigation

First we’ll load the `primes` package and a few helper packages.

``` r
library(primes)
library(tibble)
library(dplyr)
library(knitr)
```

Next, we define a second *φ* function which directly counts the number
of positive integers less than *n* that are coprime to *n*. This will
give us Euler's totient by definition.

``` r
phi2 <- function(n) vapply(n, \(x) sum(coprime(seq_len(x), x)), integer(1))
```

Now we find all instances where the `phi` function in the `primes`
package does not match the output of `phi2` for all *n* ≤ 1000.

``` r
mismatches <- tibble(n = seq_len(1000)) |> 
  mutate(actual = phi(n), expected = phi2(n)) |> 
  filter(actual != expected)
kable(mismatches)
```

|   n | actual | expected |
|----:|-------:|---------:|
| 451 |    399 |      400 |
| 737 |    659 |      660 |
| 803 |    719 |      720 |
| 902 |    399 |      400 |

## Analysis

In all cases where a match does not occur, the `phi` function is one
less than expected. This is an artifact of a floating point conversion,
as illustrated below:

``` r
phi3 <- function(n) sapply(n, \(x) x * prod(1 - 1 / unique(prime_factors(x)[[1]])))
sprintf("%.15f", phi3(mismatches[["n"]]))
```

    ## [1] "399.999999999999943" "659.999999999999886" "719.999999999999886"
    ## [4] "399.999999999999943"

## Solution

Rounding prior to integer conversion appears to suffice here. I have confirmed output
is correct for all 1 ≤ *n* ≤ 15000 when applying such a patch.

There is another formula that could be used here. It was considered, but benchmarking
shows it is about 3-4x slower. Since the rounding solution for the existing formula
appears to work, I suggest we move forward with that instead.

``` r
# Rejected due to speed penalty
phi <- function(n) {
  vapply(
    prime_factors(n),
    \(x) {
      runs <- rle(x)
      as.integer(prod(runs$values ** (runs$lengths - 1) * (runs$values - 1)))
      },
    integer(1L)
  )
}
```

I will post a PR shortly.

**Closed as completed** 2024-01-16 15:57 UTC
